### ISSUE TITLE
What is a typical wall-clock time for a FixMatch run?

### ISSUE THREAD

**Issue by lnsmith54** [google-research/fixmatch#15]
Thanks for releasing this code and especially for such fine research behind it.

Could you please let me know what is the typical wall-clock time for a FixMatch run?  My runs typically take 4 days, which seems a bit high to me.

**Comment by david-berthelot** [comment]
Seems about right. I think the augmentation is relatively slow even though it's using multiprocessing (there's a communication latency). I believe that's what is making the whole training slower.
Beyond that, may be there's interesting research in improving convergence speed of SSL methods.
