### ISSUE TITLE
Ids for the 1 samples per class runs

### ISSUE THREAD

**Issue by PaulAlbert31** [google-research/fixmatch#16]
Hi guys,
Thanks for the great work and for the code !  I was wondering if you would make available the image ids or the dataset files for training with the eight "buckets" of 10 annotated images.

Thanks,
Paul

**Comment by carlini** [comment]
These are the IDs of the images in our training set. I believe all reasonable training sets are ordered the same way, but to be sure you might want to compare to the figure in the appendix and make sure the images match.

Below, `indexs[i][j]` corresponds to the `j`th image on from split `i`, where the `0`th split is the outliers (reversed order from the way the paper presents it).

```indexs = [[7408, 8148, 9850, 10361, 33949, 36506, 37018, 45044, 46443, 47447], [5022, 8193, 8902, 9601, 25226, 26223, 34089, 35186, 40595, 48024], [7510, 13186, 14043, 21305, 22805, 31288, 34508, 40470, 41493, 45506], [9915, 9978, 16631, 19915, 28008, 35314, 35801, 36149, 39215, 42557], [6695, 14891, 19726, 22715, 23999, 34230, 46511, 47457, 49181, 49397], [12830, 20293, 26835, 30517, 30898, 31061, 43693, 46501, 47310, 48517], [1156, 11501, 19974, 21963, 32103, 42189, 46789, 47690, 48229, 48675], [4255, 6446, 8580, 11759, 12598, 29349, 29433, 33759, 35345, 38639]]```

**Comment by PaulAlbert31** [comment]
Thanks for providing this !
