### ISSUE TITLE
Feature request: use this with structured data

### ISSUE THREAD

**Issue by cibic89** [google-research/fixmatch#18]
As title suggests

**Comment by carlini** [comment]
I'm not quite sure I follow: what kind of structured data are you imagining?

**Comment by cibic89** [comment]
That's it, it's not for images. I was hoping to use SSL for one class classification problems or normally detection.
________________________________

**Comment by david-berthelot** [comment]
This repository is for the code associated with the FixMatch paper, to demonstrate how to replicate results. As such, we're not taking feature requests or evolving the code, it's a snapshot.

We are not commenting on future research in general.
