### ISSUE TITLE
Running fixmatch with RandAugment

### ISSUE THREAD

**Issue by dsuess** [google-research/fixmatch#19]
First of all, thanks for publishing the code for this paper -- it makes reproducing your work much easier.

I am trying to run fixmatch with RandAugment+Cutout instead of CTAugment (as it's much easier to implement in practice and the performance is often comparable). I've read #4 which states that fixmatch always uses CTAugment (additionally to what's provided in the `--augment` flag). So if I understand this correctly, `--augment d.d.rac` does not achieve what I want since CTAugment is always added on top? I suspect that's what's happening since I still see the CTAugment-weight printout when running training with that argument.

If that's the case, is there an easy way to disable CTAugment?

**Comment by carlini** [comment]
You can see the ablations for lots of examples on how we do these experiments, e.g., 

https://github.com/google-research/fixmatch/blob/master/ablation/ab_fixmatch_onlycutout.py

**Comment by dsuess** [comment]
Thanks, that folder contains everything I need

**Comment by YUE-FAN** [comment]
Thanks for the nice work and for releasing the code.

I am also trying to reproduce the CIFAR100 result of fixmatch with RandAugment+Cutout. In the paper, CIFAR100 with 10000 labels reaches 77.40% test accuracy. But I failed to get close to the number. Could you please enlighten me on what I might do wrong?

Here is the command I used:
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ablation/ab_fixmatch_ra.py --filters=32 --dataset=cifar100.1@10000-1 --train_dir ./experiments/fixmatch/`

and used this to extract the accuracy:
`./scripts/extract_accuracy.py ./experiments/fixmatch/cifar100.d.d.rac.1@10000-1/FixMatch_RA_archresnet_batch64_confidence0.95_filters32_lr0.03_nclass100_repeat4_scales3_uratio7_wd0.0005_wu1.0/`

and here is the result:
"last01": 72.77999877929688,
"last10": 72.43999862670898,
"last20": 72.57499694824219,
"last50": 72.69499969482422

If it is possible, could you maybe provide more details on the 77.40% experiments?

Thank you for your kind help in advance.
