### ISSUE TITLE
Question related to dataset and create_datasets.py

### ISSUE THREAD

**Issue by hwang787** [google-research/fixmatch#22]
It seems that create_datasets.py only accepts certain options for online datasets.
Is there any way if we want to use our own data in our local folder?

**Comment by david-berthelot** [comment]
Yes you can simply create a tfrecord file. The format is 
```
image: string(png encoded image)
label: int32(the class index)
```
You can use the `create_datasets.py` as an example to see how to write tfrecords, this way you can easily create a custom dataset from your data.

**Comment by chituzidehuluobo** [comment]
There are always' Windows fatal exception: access violation 'problems in the code, I would like to ask if it is the version problem of tensorflow.

**Comment by carlini** [comment]
None of us have ever tested on windows, so I wouldn't be surprised if it didn't work there.
