### ISSUE TITLE
 OutputStream realloc failed

### ISSUE THREAD

**Issue by NovaMind-Z** [google-research/fixmatch#23]
Hi,
    I am trying to run your code on ImageNet. And I begin to make the split by the command ./generate_ssl_imagenet.sh --runner=DirectRunner --direct_num_workers=16
I successfully make the labeled data split, but when it begins to make the unlabeled split (using the code:[  python -B save_sharded_data.py \
    --input_dir="${IMAGENET_DIR}" \
    --sharding_file="data_splits/files2shards_train.txt" \
    --output_file_prefix="${SSL_IMAGENET_DIR}/train" \
    -- "$@"]
), the error "AssertionError: OutputStream realloc failed." always occurs, so what can I do to fix it? 

Thanks in advance for your help

**Comment by AlexeyKurakin** [comment]
Hi,
I never seen this error. Given that labelled split generated successfully I would assume that code works and you have all dependencies properly installed.

Judging by the error message I would assume that this is actually out of memory error, see corresponding code of Apache Beam: https://github.com/apache/beam/blob/296f5a74f981c9023a54e1c2c89db7ee8e6b428a/sdks/python/apache_beam/coders/stream.pyx#L109

I'm actually not sure how to decrease memory footprint of the beam DirectRunner. Maybe decreasing number of workers may help.

Alternatively, you can consider rewriting this code in a more memory-efficient way without using Apache Beam.

**Comment by NovaMind-Z** [comment]
> Hi,
> I never seen this error. Given that labelled split generated successfully I would assume that code works and you have all dependencies properly installed.
> 
> Judging by the error message I would assume that this is actually out of memory error, see corresponding code of Apache Beam: https://github.com/apache/beam/blob/296f5a74f981c9023a54e1c2c89db7ee8e6b428a/sdks/python/apache_beam/coders/stream.pyx#L109
> 
> I'm actually not sure how to decrease memory footprint of the beam DirectRunner. Maybe decreasing number of workers may help.
> 
> Alternatively, you can consider rewriting this code in a more memory-efficient way without using Apache Beam.

Hi, 
Thanks for your reply, if I skip the reshuffle process of the unlabeled data, instead I copy the training tfrecord data  in ${IMAGENET_DIR}/train directly to ${SSL_IMAGENET_DIR} (just like what you do for validation data),  will the model still work well and archive the paper results? Also I will try to decrease the number of works to see whether the script works. BTW, why you reshuffle the unlabeled data?

**Comment by NovaMind-Z** [comment]
Hi,
I met some problems when running the code:
mkdir -p ${HOME}/models/fixmatch
python -B fixmatch.py \
  --imagenet_data="${SSL_IMAGENET_DIR}" \
  --model_dir="${HOME}/models/fixmatch" \
  --steps_per_run=100 \
  --per_worker_batch_size=8 \
  --dataset="imagenet128116.1" \
  --hparams="\"bfloat16\": false, \"num_epochs\": 3000, \"learning_rate\": { \"warmup_epochs\": 50, \"decay_epochs\": 500 }, \"augment\": { \"type\": \"randaugment\" }"
the code always stops like this:
![image](https://user-images.githubusercontent.com/42997811/79215031-bb809780-7e7d-11ea-87a9-69cca7f34428.png)
my environment is :{
      Tensorflow 2.1 
      CUDA 10.1
      CUDNN 7.6
      Tensorflow-addons 0.9.1
      GPU: Tesla V100
}
Do you have any idea about it? What's more, could you share me with the training log file (I think the tfevents file should be great for me) of the training on imagenet? I think it may help me to reproduce the paper results by PyTorch.

**Comment by AlexeyKurakin** [comment]
Shuffling of unlabelled data not strictly necessary, but I suppose it can somewhat improve performance.
The goal of shuffling of unlabelled data is to ensure that labels are distributed uniformly locally (i.e. you get roughly uniform distributions of labels within arbitrary slice of the dataset). If labels in un-shuffled data are distributed unevenly then it may decrease performance of trained classifier.

Regarding the delay you see in the training process. The training code runs `steps_per_run` training steps before reporting any progress. After running `steps_per_run` it reports values of the loss function and runs eval on entire test set.
I think you code is not stuck but just running 100 steps of training (look at the log line `training.py:306] Running steps 1-100`). If you're unsure, then set `--steps_per_run` flag to some small value and check what happens.

**Comment by NovaMind-Z** [comment]
> Shuffling of unlabelled data not strictly necessary, but I suppose it can somewhat improve performance.
> The goal of shuffling of unlabelled data is to ensure that labels are distributed uniformly locally (i.e. you get roughly uniform distributions of labels within arbitrary slice of the dataset). If labels in un-shuffled data are distributed unevenly then it may decrease performance of trained classifier.
> 
> Regarding the delay you see in the training process. The training code runs `steps_per_run` training steps before reporting any progress. After running `steps_per_run` it reports values of the loss function and runs eval on entire test set.
> I think you code is not stuck but just running 100 steps of training (look at the log line `training.py:306] Running steps 1-100`). If you're unsure, then set `--steps_per_run` flag to some small value and check what happens.

Hi,
     Thanks for your patient explanation. But I think decrease steps_per_run doesn't solve my problem. I set it to 10 and wait for around 3 hours, but didn't get any reporting info. 
![image](https://user-images.githubusercontent.com/42997811/79336952-34075700-7f57-11ea-9e90-5d304b26e604.png)




Anyway, the reason I want to run your code is to obtain some log information during training so that I can check whether my code achieve the same performance with yours within short training time.  So could you please share me with you training log file (like tfevents file) so that I don't have to run your code.

**Comment by AlexeyKurakin** [comment]
Unfortunately I won't be able to provide training log file.

**Comment by NovaMind-Z** [comment]
> Unfortunately I won't be able to provide training log file.

Anyway, thanks again for your help.

**Comment by Midkey** [comment]
> 
> 
> Hi,
> I met some problems when running the code:
> mkdir -p ${HOME}/models/fixmatch
> python -B fixmatch.py
> --imagenet_data="${SSL_IMAGENET_DIR}"
> --model_dir="${HOME}/models/fixmatch"
> --steps_per_run=100
> --per_worker_batch_size=8
> --dataset="imagenet128116.1"
> --hparams=""bfloat16": false, "num_epochs": 3000, "learning_rate": { "warmup_epochs": 50, "decay_epochs": 500 }, "augment": { "type": "randaugment" }"
> the code always stops like this:
> ![image](https://user-images.githubusercontent.com/42997811/79215031-bb809780-7e7d-11ea-87a9-69cca7f34428.png)
> my environment is :{
> Tensorflow 2.1
> CUDA 10.1
> CUDNN 7.6
> Tensorflow-addons 0.9.1
> GPU: Tesla V100
> }
> Do you have any idea about it? What's more, could you share me with the training log file (I think the tfevents file should be great for me) of the training on imagenet? I think it may help me to reproduce the paper results by PyTorch.

Hello! Do you solve the problem? I meet the same problem and can not find out where stop the code.
I try to add print function in imagenet/fixmatch.py->train_step->step_fn function.

Then I found that the code run into
`self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`

and print the info msg like your picture show.
`INFO:tensorflow:batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
I1205 13:16:24.504762 139793746917184 cross_device_ops.py:760] batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
`
After run the  self.strategy.experimental_run_v2 finction twice, and return from it, the code stop and print
`
2020-12-05 13:16:58.958735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-12-05 13:17:01.910404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
`

Then I replace the code in fixmatch.py :
`
 for _ in tf.range(num_steps_to_run):
      self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))
`
with 
`   
 for i in range(100):
        self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))
`
It can run!!! 

However, another problem confuses me. When running the code, the GPU volatile GPU-Util is Zero.
![图片](https://user-images.githubusercontent.com/19383886/101245227-33ba0700-3746-11eb-8fbe-ae3f239ad9e5.png)

my environment is :
Tensorflow 2.1
CUDA 10.1
CUDNN 7.6
Tensorflow-addons 0.6.0
GPU: Tesla V100

**Comment by david-berthelot** [comment]
That looks like a configuration problem, also you're using the wrong version of TF:
https://github.com/google-research/fixmatch/blob/master/requirements.txt

**Comment by slpal** [comment]
> > Hi,
> > I met some problems when running the code:
> > mkdir -p ${HOME}/models/fixmatch
> > python -B fixmatch.py
> > --imagenet_data="${SSL_IMAGENET_DIR}"
> > --model_dir="${HOME}/models/fixmatch"
> > --steps_per_run=100
> > --per_worker_batch_size=8
> > --dataset="imagenet128116.1"
> > --hparams=""bfloat16": false, "num_epochs": 3000, "learning_rate": { "warmup_epochs": 50, "decay_epochs": 500 }, "augment": { "type": "randaugment" }"
> > the code always stops like this:
> > ![image](https://user-images.githubusercontent.com/42997811/79215031-bb809780-7e7d-11ea-87a9-69cca7f34428.png)
> > my environment is :{
> > Tensorflow 2.1
> > CUDA 10.1
> > CUDNN 7.6
> > Tensorflow-addons 0.9.1
> > GPU: Tesla V100
> > }
> > Do you have any idea about it? What's more, could you share me with the training log file (I think the tfevents file should be great for me) of the training on imagenet? I think it may help me to reproduce the paper results by PyTorch.
> 
> Hello! Do you solve the problem? I meet the same problem and can not find out where stop the code.
> I try to add print function in imagenet/fixmatch.py->train_step->step_fn function.
> 
> Then I found that the code run into
> `self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> 
> and print the info msg like your picture show.
> `INFO:tensorflow:batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10 I1205 13:16:24.504762 139793746917184 cross_device_ops.py:760] batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10 `
> After run the self.strategy.experimental_run_v2 finction twice, and return from it, the code stop and print
> `2020-12-05 13:16:58.958735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10 2020-12-05 13:17:01.910404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
> 
> Then I replace the code in fixmatch.py :
> `for _ in tf.range(num_steps_to_run): self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> with
> ` for i in range(100): self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> It can run!!!
> 
> However, another problem confuses me. When running the code, the GPU volatile GPU-Util is Zero.
> ![图片](https://user-images.githubusercontent.com/19383886/101245227-33ba0700-3746-11eb-8fbe-ae3f239ad9e5.png)
> 
> my environment is :
> Tensorflow 2.1
> CUDA 10.1
> CUDNN 7.6
> Tensorflow-addons 0.6.0
> GPU: Tesla V100

Hi, Do you solve the problem? I also meet the same problem and have no idea why the code stoped. @Midkey

**Comment by fiona-lxd** [comment]
> > > Hi,
> > > I met some problems when running the code:
> > > mkdir -p ${HOME}/models/fixmatch
> > > python -B fixmatch.py
> > > --imagenet_data="${SSL_IMAGENET_DIR}"
> > > --model_dir="${HOME}/models/fixmatch"
> > > --steps_per_run=100
> > > --per_worker_batch_size=8
> > > --dataset="imagenet128116.1"
> > > --hparams=""bfloat16": false, "num_epochs": 3000, "learning_rate": { "warmup_epochs": 50, "decay_epochs": 500 }, "augment": { "type": "randaugment" }"
> > > the code always stops like this:
> > > ![image](https://user-images.githubusercontent.com/42997811/79215031-bb809780-7e7d-11ea-87a9-69cca7f34428.png)
> > > my environment is :{
> > > Tensorflow 2.1
> > > CUDA 10.1
> > > CUDNN 7.6
> > > Tensorflow-addons 0.9.1
> > > GPU: Tesla V100
> > > }
> > > Do you have any idea about it? What's more, could you share me with the training log file (I think the tfevents file should be great for me) of the training on imagenet? I think it may help me to reproduce the paper results by PyTorch.
> > 
> > 
> > Hello! Do you solve the problem? I meet the same problem and can not find out where stop the code.
> > I try to add print function in imagenet/fixmatch.py->train_step->step_fn function.
> > Then I found that the code run into
> > `self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> > and print the info msg like your picture show.
> > `INFO:tensorflow:batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10 I1205 13:16:24.504762 139793746917184 cross_device_ops.py:760] batch_all_reduce: 161 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10 `
> > After run the self.strategy.experimental_run_v2 finction twice, and return from it, the code stop and print
> > `2020-12-05 13:16:58.958735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10 2020-12-05 13:17:01.910404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
> > Then I replace the code in fixmatch.py :
> > `for _ in tf.range(num_steps_to_run): self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> > with
> > ` for i in range(100): self.strategy.experimental_run_v2(step_fn, args=(next(iterator),))`
> > It can run!!!
> > However, another problem confuses me. When running the code, the GPU volatile GPU-Util is Zero.
> > ![图片](https://user-images.githubusercontent.com/19383886/101245227-33ba0700-3746-11eb-8fbe-ae3f239ad9e5.png)
> > my environment is :
> > Tensorflow 2.1
> > CUDA 10.1
> > CUDNN 7.6
> > Tensorflow-addons 0.6.0
> > GPU: Tesla V100
> 
> Hi, Do you solve the problem? I also meet the same problem and have no idea why the code stoped. @Midkey

Hi, did you solve this problem? I met the same problem...
