### ISSUE TITLE
Reproduce Fixmatch with RandAug

### ISSUE THREAD

**Issue by YUE-FAN** [google-research/fixmatch#25]
Thanks for the nice work and for releasing the code.

I am also trying to reproduce the CIFAR100 result of fixmatch with RandAugment+Cutout. In the paper, CIFAR100 with 10000 labels reaches 77.40% test accuracy. But I failed to get close to the number. Could you please enlighten me on what I might do wrong? I have checked [#19 ](https://github.com/google-research/fixmatch/issues/19), and here is the command I used:
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ablation/ab_fixmatch_ra.py --filters=32 --dataset=cifar100.1@10000-1 --train_dir ./experiments/fixmatch/`

and used this to extract the accuracy:
`./scripts/extract_accuracy.py ./experiments/fixmatch/cifar100.d.d.rac.1@10000-1/FixMatch_RA_archresnet_batch64_confidence0.95_filters32_lr0.03_nclass100_repeat4_scales3_uratio7_wd0.0005_wu1.0/`

and here is the result:
`
"last01": 72.77999877929688,
"last10": 72.43999862670898,
"last20": 72.57499694824219,
"last50": 72.69499969482422
`

If it is possible, could you maybe provide more details on the 77.40% experiments?

Thank you for your kind help in advance.

**Comment by YUE-FAN** [comment]
Thanks a lot. Indeed, `--filters=128` gives around 77% test accuracy now :)

**Comment by Chen-Song** [comment]
> Thanks a lot. Indeed, `--filters=128` gives around 77% test accuracy now :)

Hi, have you try to reproduce the CIFAR100 with 400 labels with `--filters=128`?  Because I don’t have enough computing resources, I can’t reproduce it quickly.

**Comment by YUE-FAN** [comment]
> > Thanks a lot. Indeed, `--filters=128` gives around 77% test accuracy now :)
> 
> Hi, have you try to reproduce the CIFAR100 with 400 labels with `--filters=128`? Because I don’t have enough computing resources, I can’t reproduce it quickly.

Yes, but I implement everything in PyTorch. It has a 53.47% test error in the end, but if you do early stopping, it can reach 44.18%. (The number in the paper is 48.85%)

**Comment by LeeDoYup** [comment]
When you set filters=128, what was the number of trainable params ??? (I know that 32 filters model has 1.5 M params)

**Comment by YUE-FAN** [comment]
> When you set filters=128, what was the number of trainable params ??? (I know that 32 filters model has 1.5 M params)

It has 23.41 M params.

**Comment by LeeDoYup** [comment]
Oh Thanks, i wanted to check it has much parameters in pytorch implementation than 1.5 M.
Thank you for cross-checking !!
(I think it takes much more time than the cifar10 case)

> > When you set filters=128, what was the number of trainable params ??? (I know that 32 filters model has 1.5 M params)
> 
> It has 23.41 M params.
