### ISSUE TITLE
CIFAR-100 Model

### ISSUE THREAD

**Issue by shellshock1911** [google-research/fixmatch#26]
In section 4.1 of the paper, you state:

> To begin with, we compare FixMatch to various existing methods on the standard CIFAR-10, CIFAR-100, and SVHN benchmarks. As recommended by [31], we reimplemented all existing baselines and performed all experiments using the same codebase. In particular, we use the same network architecture (a Wide ResNet-28-2 [47] with 1.5M parameters) ...

Then in the Appendix, you state:

> As mentioned in section 4, we used almost identical hyperparameters of FixMatch on CIFAR-10, CIFAR-100, SVHN and STL-10. Note that we used similar network architectures for these datasets, **except that more convolution filters were used for CIFAR-100 to handle larger label space** ...

I'm trying to reproduce this particular result, however "more convolution filters" isn't defined in the paper with a number. If my understanding is correct, the codebase is setup so that the default `filters` for the model is 32, and then you allow users to optionally configure this by passing a `--filters` argument to the main script. In other words, there's no single source of config files that we can review to understand how CIFAR-100 was treated differently.

Would you be able to provide these implementation details on CIFAR-100?

**Comment by david-berthelot** [comment]
Sorry about that, it's --filters=128
Thanks for pointing this out, we'll update the paper to specify that number.

**Comment by shellshock1911** [comment]
Thanks! Looking forward to trying it out with this change.
