### ISSUE TITLE
About the epochs and update iterations

### ISSUE THREAD

**Issue by hwaranlee** [google-research/fixmatch#28]
Hi. Thanks for publishing this repo.
While I'm testing Fixmatch algorithm, I have several questions.

1. According to the experiment setup described in the paper, the K = 2^20 which is the total update iterations.
From the codes below,
https://github.com/google-research/fixmatch/blob/08d9b83d7cc87e853e6afc5a86b12aacff56cdea/mixmatch.py#L174
https://github.com/google-research/fixmatch/blob/08d9b83d7cc87e853e6afc5a86b12aacff56cdea/mixmatch.py#L158
the total update iterations seem to be 2^26.
Is it right?

2. Is there a special reason for setting to 1 epoch to be 2^16 iterations? 

Thanks,

**Comment by carlini** [comment]
1. We train for 2^16 kimgs, which as you observe is 2^26 *images*. However the batch size is 64 = 2^6 images, so there are a total of 2^20 updates.

2. CIFAR-10 has a batch size of 50,000 which is approximately 2^16. Note that while debugging we call this an epoch, it is completely detached from the functionality. So you can safely change --report_kimg to anything you want and get reports after that many images.

**Comment by hwaranlee** [comment]
Oh I see. Thanks!!
