### ISSUE TITLE
Error in ./cta/cta_remixmatch.py

### ISSUE THREAD

**Issue by varunnair18** [google-research/fixmatch#3]
Hi,

Thanks for releasing the code on FixMatch, great to have it released so soon alongside the paper. I was able to run `fixmatch.py` on CIFAR10 after correcting line 22 in `./cta/cta_remixmatch.py`

from: `from remixmatch import ReMixMatch`

to: `from remixmatch_no_cta import ReMixMatch`

Hope you make this change so others can run it successfully.

**Comment by carlini** [comment]
This is definitely true, thanks for catching it. It's fixed now by ba902a4c9bbf1dc49b99adb6d9fd422606c7e213.

(This one's completely on me. I made one last change that clearly couldn't have broken anything, right before pushing, and renamed the file to be consistent with the remixmatch repository.)
