### ISSUE TITLE
What is the meaning of expanding the dataset about labeled and unlabeled data?

### ISSUE THREAD

**Issue by Chen-Song** [google-research/fixmatch#30]
Hi, I recently read FixMatch's paper and code. In the implementation of FixMatch, for example, 4000 labeled data; you need to copy the labeled data to 65536, and copy the remaining unlabeled to 65536*7. I don't quite understand why do this. Do you know why do this？ Or is it the default setting for semi-supervised fields?

**Comment by carlini** [comment]
I don't quite follow the question. What do you mean "copy the labeled data to 65536"? We train for 65536 kimgs as a hyperparameter, in order to get as high accuracy as possible.
