### ISSUE TITLE
Motivation for EMA

### ISSUE THREAD

**Issue by bkj** [google-research/fixmatch#37]
Hi --

Are you able to provide a little insight into why you use an exponential moving average of the model weights?  Do you have a sense of how important this is for good performance?  I'm not super familiar w/ this technique, and didn't see a ton of discussion in the paper.

Thanks!

**Comment by david-berthelot** [comment]
I don't think we did an ablation study on it. We used EMA since MixMatch, back then it was used as a replacement for learning rate decay to simplify the code.
