### ISSUE TITLE
Did you use random augment as strong aug as claimed in the paper?

### ISSUE THREAD

**Issue by CoinCheung** [google-research/fixmatch#4]
Hi, 

Thanks for bring the work to us. I am going through the code you released, and I noticed that the augmentations are assigned with an argment of `augment` whose default value is `d.d.d`. Does it mean that in this repo you use default aug methods for both strong and weak augments for the unlabeled samples ?

**Comment by david-berthelot** [comment]
Hello, in fixmatch CTAugment is done in addition to `d.d.d`. I've updated the README to explain a bit more: https://github.com/google-research/fixmatch#flags

**Comment by CoinCheung** [comment]
So for fixmatch, CTAugment is only applied to stronly augmented unlabeled samples(after the default augments), while labeled and weakly augmented unlabeled samples only employ default augments(flip and random crop), is that true ?

**Comment by wangxu-scu** [comment]
Hi,
thanks for the amazing work!! I have the same concern about the CTAugment application. The paper describes that the labeled data are only performed weak augmentation strategy, while in the code, it seems that the CTAugment strategy is also applied to the labeled samples as well as the evaluating samples (https://github.com/google-research/fixmatch/blob/master/libml/augment.py#L316 and https://github.com/google-research/fixmatch/blob/master/libml/augment.py#L317).  Do I understand it in the wrong way? Thanks for your fascinating work again! Looking forward to your reply.

**Comment by david-berthelot** [comment]
The code you pointed to is used for fully supervised augmentation, for FixMatch it is overloaded 
https://github.com/google-research/fixmatch/blob/master/fixmatch.py#L38

Sorry, the code is a bit complicated. Thanks for asking the question.

**Comment by wangxu-scu** [comment]
Thanks for your reply~~
So the code https://github.com/google-research/fixmatch/blob/master/fixmatch.py#L38 means that the CTAugment is applied to evaluation samples. Do I understand correct？

**Comment by wangxu-scu** [comment]
> The code you pointed to is used for fully supervised augmentation, for FixMatch it is overloaded
> https://github.com/google-research/fixmatch/blob/master/fixmatch.py#L38
> 
> Sorry, the code is a bit complicated. Thanks for asking the question.

Thanks for your reply~~
So the code https://github.com/google-research/fixmatch/blob/master/fixmatch.py#L38 means that the CTAugment is applied to evaluation samples. Do I understand correct？

**Comment by david-berthelot** [comment]
No it is applied to labeled images used as probes. I prefer not to use the word evaluation since it could be confused with the testing phase / model evaluation.

CTAugment takes a labeled image and strongly augments it. We call this a probe. We uses the model prediction on it to adjust the augmentation internal parameters.

**Comment by wangxu-scu** [comment]
> No it is applied to labeled images used as probes. I prefer not to use the word evaluation since it could be confused with the testing phase / model evaluation.
> 
> CTAugment takes a labeled image and strongly augments it. We call this a probe. We uses the model prediction on it to adjust the augmentation internal parameters.

Thanks very much!

**Comment by CoinCheung** [comment]
So there will be four sorts of training samples in one iter, the weakly augmented labeled samples and the strongly augmented unlabeled samples will be used to train the model(compute loss). The strongly augmented labeled samples will be used to update CTAugment weights, and the weakly augmented unlabled samples will be used to generated the psuedo labels for computing the unlabeled loss. Am I correct on this?

**Comment by david-berthelot** [comment]
Yes
