### ISSUE TITLE
Model for CIFAR-100

### ISSUE THREAD

**Issue by bkj** [google-research/fixmatch#45]
In Appendix B.1 of the [FixMatch paper](https://arxiv.org/pdf/2001.07685.pdf), it says

> Note that we used similar network architectures for these datasets, except that more convolution filters were used for CIFAR-100 to handle larger label space

Are you able to elaborate on this?  I'm trying to get close to the CIFAR-100 results using my own FixMatch implementation, and want to make sure I'm being faithful to the experiments in the paper.  I don't see any special model parameterization for CIFAR-100 in this repo -- so maybe it's not necessary?

Thanks!

**Comment by LeeDoYup** [comment]
`--filter=128`
same issue: https://github.com/google-research/fixmatch/issues/26
