### ISSUE TITLE
"Aborted" while running multiple processes in train_session.run

### ISSUE THREAD

**Issue by divagrwl** [google-research/fixmatch#48]
![image](https://user-images.githubusercontent.com/31839963/100019080-58030480-2d92-11eb-9996-d67f484708e8.png)

The process is aborting right at the beginning of training. Is it because of the multiple processes running at a time? Can't figure out the issue.

**Comment by carlini** [comment]
This looks like an incomplete stack trace. Could you show the complete trace?

What are the specs of your machine? "Aborted" can often mean that it ran out of memory.
