### ISSUE TITLE
Some questions about the reported results

### ISSUE THREAD

**Issue by QiushiYang** [google-research/fixmatch#69]
Thanks a lot for your released codes and your excellent work. I have some questions about the reported results in your paper.
(1) Does the reported results are obtained by calculating the mean accuracy value of the latest several (e.g., 20) iterations/batchs/epochs during the training phase or just select the best accuracy of someone iteration/batch/epoch, or any other protocols?
(2) Your paper illustrates that all results are obtained by final EMA model. I re-implemented and re-trained FixMatch and found that some results of student model are similar with yours while the results of final EMA model are better. I want to know why.
(3) About the total training iterations with images/epochs: in your codes, the total training images seems 1<<16 (65536). Does this mean the model is trained with totally 65536 images or 65536 labeled images? If the former, for CIFAR10-x40, is the total epoch 65536/~40000 = ~1.6, or if the latter, it is 65536/40=~1638 epochs?

**Comment by carlini** [comment]
(1) Yeah, we do average the last few epochs of training as is done in prior work. We take the average in order to report more precise results. Sometimes the accuracy fluctuates higher, sometimes lower, but we don't want to bias the results high (or low) just because we happened to stop training after exactly N steps instead of N-1 or N+1.

(2) I'm not quite sure what you're asking here. You found the non-EMA model is better?

(3) It trains for 1<<16 kimgs, or 1<<26 total images. So it's 1<<26 / 50000 ~= 1342 epochs.

**Comment by QiushiYang** [comment]
Thank you so much for your kindly replys. I got it and still have some further confusions:
About (1): Would you introduce how many last epochs/images you used to calculate the mean accuracy results?
About (2): I mean I found the results of my re-trained FixMatch student model are close to yours, while performances of the EMA teacher model are better than the reporting results in your paper. May it be a coincident?

**Comment by carlini** [comment]
(1) We use the last 20 steps the model was trained on, you can find additional information in the README for exactly how to compute it:

```
We compute the median accuracy of the last 20 checkpoints in the paper, this is done through this code:

# Following the previous example in which we trained cifar10.3@250-5000, extracting accuracy:
./scripts/extract_accuracy.py ./experiments/fixmatch/cifar10.d.d.d.3@40-1/CTAugment_depth2_th0.80_decay0.990/FixMatch_archresnet_batch64_confidence0.95_filters32_lr0.03_nclass10_repeat4_scales3_uratio7_wd0.0005_wu1.0/

# The command above will create a stats/accuracy.json file in the model folder.
# The format is JSON so you can either see its content as a text file or process it to your liking.
```

(2) Possibly it's due to just to variance. How much better is it?

**Comment by QiushiYang** [comment]
Many thanks. I will see the codes in detail again.
About (2), it seems about 2 points better on CIFAR-10-x40, but I just only train models with two seeds and maybe the results highly depend on them.
