### ISSUE TITLE
 Does CTAugment let each augment operation have 17 bins?

### ISSUE THREAD

**Issue by CoinCheung** [google-research/fixmatch#7]
Hi, 

I am learning about the details of the code, and I appreciate that you could help me with some puzzles.

I noticed that in the `ctaugment.py` each augment operator is registared to have 17 bins. Does this mean that the magnitude value of each operator will range from 0-17 before mapped to specific range of each augment operator ?

By the way, it seems that there are more augment operators in ctaugment than random augment(including smooth, bluring, cutout, etc), isn't it?

**Comment by david-berthelot** [comment]
No, it's in [0, 1] divided into 17 equal intervals.

**Comment by CoinCheung** [comment]
Hi, 

Just to make sure I have not understand the code incorrectly, Could you please tell me that: did you train the fixmatch model for 1M(1024x1024) iters in total, and in each iter there are 64 labeled and 448(64x7) unlabeled training samples ?

**Comment by david-berthelot** [comment]
Yes.
