### ISSUE TITLE
How to set the epoch?

### ISSUE THREAD

**Issue by erhanbicerr** [google-research/fixmatch#81]
Hello,
I am using fixmatch.py to build a SSL model for a custom dataset that I added. Yet, default value for the epoch is 1024. How to tweak the epoch. I could not find as an argument in the fixmatch.py. I would be very appreciated if you could help me.
Have a nice day!

**Comment by carlini** [comment]
The number of training steps is set here

https://github.com/google-research/fixmatch/blob/d4985a158065947dba803e626ee9a6721709c570/fixmatch.py#L176
